#requires -Version 7.6
#requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0' }

BeforeAll {
    $manifest = Join-Path (Split-Path $PSScriptRoot -Parent) 'PSVellumPDF.psd1'
    Import-Module $manifest -Force
}

AfterAll {
    Remove-Module PSVellumPDF -Force -ErrorAction SilentlyContinue
}

Describe 'PSVellumPDF module surface' {
    It 'exports the expected public functions' {
        $exported = (Get-Module PSVellumPDF).ExportedFunctions.Keys
        $exported | Should -Contain 'New-VellumPdfDocument'
        $exported | Should -Contain 'Add-VellumPdfHeading'
        $exported | Should -Contain 'Add-VellumPdfParagraph'
        $exported | Should -Contain 'Save-VellumPdfDocument'
    }
}

Describe 'PDF generation pipeline' {
    BeforeEach {
        $script:outPath = Join-Path $TestDrive "doc-$([guid]::NewGuid()).pdf"
    }

    It 'produces a non-empty PDF file with a valid header' {
        New-VellumPdfDocument |
            Add-VellumPdfHeading -Text 'Smoke Test' -Level 1 |
            Add-VellumPdfParagraph -Text 'Generated by PSVellumPDF.' |
            Save-VellumPdfDocument -Path $script:outPath

        Test-Path $script:outPath | Should -BeTrue
        (Get-Item $script:outPath).Length | Should -BeGreaterThan 0

        # Every PDF starts with the "%PDF-" magic bytes.
        $head = [System.Text.Encoding]::ASCII.GetString(
            [System.IO.File]::ReadAllBytes($script:outPath)[0..4])
        $head | Should -Be '%PDF-'
    }

    It 'creates a PDF/A-2b conformant document' {
        New-VellumPdfDocument -Conformance PdfA2b -PageSize Letter |
            Add-VellumPdfParagraph -Text 'Archival text.' |
            Save-VellumPdfDocument -Path $script:outPath

        (Get-Item $script:outPath).Length | Should -BeGreaterThan 0
    }

    It 'honours per-element styling and a tagged document' {
        New-VellumPdfDocument -Tagged |
            Add-VellumPdfHeading   -Text 'Styled' -Level 2 -Alignment Center -BookmarkTitle 'Bk' |
            Add-VellumPdfParagraph -Text 'Custom run.' -Font Courier -FontSize 9 -Alignment Justify |
            Save-VellumPdfDocument -Path $script:outPath

        (Get-Item $script:outPath).Length | Should -BeGreaterThan 0
    }

    It 'renders an alignment-only paragraph with the document default font' {
        # Regression: alignment-only used to force Helvetica, overriding the
        # default. Assert the actual /BaseFont, not just a valid header.
        New-VellumPdfDocument -DefaultFont TimesRoman -DefaultFontSize 12 |
            Add-VellumPdfParagraph -Text 'Centered, default typeface.' -Alignment Center |
            Save-VellumPdfDocument -Path $script:outPath

        $raw = [System.Text.Encoding]::Latin1.GetString(
            [System.IO.File]::ReadAllBytes($script:outPath))
        $raw | Should -Match '/BaseFont\s*/Times-Roman'
        $raw | Should -Not -Match '/BaseFont\s*/Helvetica'
    }

    It 'renders a FontSize-only paragraph with the document default font' {
        # Regression: -FontSize without -Font used to force Helvetica.
        New-VellumPdfDocument -DefaultFont TimesRoman |
            Add-VellumPdfParagraph -Text 'Bigger, same typeface.' -FontSize 14 |
            Save-VellumPdfDocument -Path $script:outPath

        $raw = [System.Text.Encoding]::Latin1.GetString(
            [System.IO.File]::ReadAllBytes($script:outPath))
        $raw | Should -Match '/BaseFont\s*/Times-Roman'
        $raw | Should -Not -Match '/BaseFont\s*/Helvetica'
    }

    It 'disposes the document when the directory-not-found check throws' {
        $doc = New-VellumPdfDocument | Add-VellumPdfParagraph -Text 'x'
        { $doc | Save-VellumPdfDocument -Path (Join-Path $TestDrive 'no-dir' 'x.pdf') } |
            Should -Throw '*directory not found*'
        # A disposed document must not be saveable afterwards.
        { $doc.Save((Join-Path $TestDrive 'after-dispose.pdf')) } | Should -Throw
    }

    It 'writes the /Lang entry when -Language is supplied' {
        New-VellumPdfDocument -Language 'en-US' |
            Add-VellumPdfParagraph -Text 'Localised.' |
            Save-VellumPdfDocument -Path $script:outPath

        $raw = [System.Text.Encoding]::Latin1.GetString(
            [System.IO.File]::ReadAllBytes($script:outPath))
        $raw | Should -Match '/Lang'
    }

    It 'produces a PDF containing /ObjStm when -UseObjectStreams is supplied' {
        New-VellumPdfDocument -UseObjectStreams |
            Add-VellumPdfParagraph -Text 'Object stream document.' |
            Save-VellumPdfDocument -Path $script:outPath

        Test-Path $script:outPath | Should -BeTrue
        (Get-Item $script:outPath).Length | Should -BeGreaterThan 0

        $bytes = [System.IO.File]::ReadAllBytes($script:outPath)
        $raw = [System.Text.Encoding]::Latin1.GetString($bytes)
        $raw | Should -Match '/ObjStm'
    }

    It 'applies -MarginTop and -MarginBottom to a paragraph and produces a valid PDF' {
        New-VellumPdfDocument |
            Add-VellumPdfParagraph -Text 'Spaced paragraph.' -MarginTop 20 -MarginBottom 20 |
            Save-VellumPdfDocument -Path $script:outPath

        Test-Path $script:outPath | Should -BeTrue
        (Get-Item $script:outPath).Length | Should -BeGreaterThan 0

        $head = [System.Text.Encoding]::ASCII.GetString(
            [System.IO.File]::ReadAllBytes($script:outPath)[0..4])
        $head | Should -Be '%PDF-'
    }

    It 'applies -MarginTop and -MarginBottom to a heading and produces a valid PDF' {
        New-VellumPdfDocument |
            Add-VellumPdfHeading -Text 'Spaced Heading' -Level 2 -MarginTop 15 -MarginBottom 15 |
            Add-VellumPdfParagraph -Text 'Body after spaced heading.' |
            Save-VellumPdfDocument -Path $script:outPath

        Test-Path $script:outPath | Should -BeTrue
        (Get-Item $script:outPath).Length | Should -BeGreaterThan 0

        $head = [System.Text.Encoding]::ASCII.GetString(
            [System.IO.File]::ReadAllBytes($script:outPath)[0..4])
        $head | Should -Be '%PDF-'
    }

    It 'throws an actionable error when the target directory does not exist' {
        $doc = New-VellumPdfDocument | Add-VellumPdfParagraph -Text 'x'
        try {
            { $doc | Save-VellumPdfDocument -Path (Join-Path $TestDrive 'missing-dir' 'out.pdf') } |
                Should -Throw '*directory not found*'
        }
        finally { $doc.Dispose() }
    }

    It 'keeps the document open with -KeepOpen' {
        $doc = New-VellumPdfDocument | Add-VellumPdfParagraph -Text 'Reusable.'
        $doc | Save-VellumPdfDocument -Path $script:outPath -KeepOpen
        # Still usable after save, then dispose ourselves.
        { $doc | Add-VellumPdfParagraph -Text 'More.' | Out-Null } | Should -Not -Throw
        $doc.Dispose()
    }
}

Describe 'New-VellumTextStyle (private helper)' {
    It 'returns $null when neither font nor size is requested' {
        InModuleScope PSVellumPDF { New-VellumTextStyle } | Should -BeNullOrEmpty
    }

    It 'builds a TextStyle with the requested font and size' {
        $style = InModuleScope PSVellumPDF { New-VellumTextStyle -Font Helvetica -FontSize 14 }
        $style | Should -Not -BeNullOrEmpty
        $style.FontSize | Should -Be 14
    }
}

Describe 'ConvertTo-VellumColor (private helper)' {
    It 'passes a 0..1 RGB triple through' {
        $c = InModuleScope PSVellumPDF { ConvertTo-VellumColor @(0.1, 0.2, 0.3) }
        $c[0] | Should -Be 0.1; $c[1] | Should -Be 0.2; $c[2] | Should -Be 0.3
    }

    It 'parses a #RRGGBB hex string' {
        $c = InModuleScope PSVellumPDF { ConvertTo-VellumColor '#3366cc' }
        [math]::Round($c[0], 4) | Should -Be ([math]::Round(0x33 / 255, 4))
        [math]::Round($c[1], 4) | Should -Be ([math]::Round(0x66 / 255, 4))
        [math]::Round($c[2], 4) | Should -Be ([math]::Round(0xcc / 255, 4))
    }

    It 'expands a #RGB shorthand to the same colour as #RRGGBB' {
        $short = InModuleScope PSVellumPDF { ConvertTo-VellumColor '#36c' }
        $long  = InModuleScope PSVellumPDF { ConvertTo-VellumColor '#3366cc' }
        $short[0] | Should -Be $long[0]; $short[1] | Should -Be $long[1]; $short[2] | Should -Be $long[2]
    }

    It 'resolves a known colour name' {
        $c = InModuleScope PSVellumPDF { ConvertTo-VellumColor 'red' }
        $c[0] | Should -Be 1; $c[1] | Should -Be 0; $c[2] | Should -Be 0
    }

    It 'throws on an unrecognised colour' {
        { InModuleScope PSVellumPDF { ConvertTo-VellumColor 'notacolour' } } | Should -Throw '*unrecognised colour*'
    }

    It 'does not treat a bare number as hex (hex requires #)' {
        # '255' must NOT silently become hex 225555; require a leading # for hex.
        { InModuleScope PSVellumPDF { ConvertTo-VellumColor '255' } } | Should -Throw '*unrecognised colour*'
    }

    It 'throws a hex-specific error for a #-prefixed non-hex value' {
        { InModuleScope PSVellumPDF { ConvertTo-VellumColor '#xyz' } } | Should -Throw '*not a valid hex colour*'
    }

    It 'throws on an out-of-range component' {
        { InModuleScope PSVellumPDF { ConvertTo-VellumColor @(2.5, 0, 0) } } | Should -Throw '*between 0 and 1*'
    }
}
