#requires -Version 7.6
#requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0' }

BeforeAll {
    $manifest = Join-Path (Split-Path $PSScriptRoot -Parent) 'PSVellumPDF.psd1'
    Import-Module $manifest -Force
}

AfterAll {
    Remove-Module PSVellumPDF -Force -ErrorAction SilentlyContinue
}

Describe 'PSVellumPDF module surface' {
    It 'exports the expected public functions' {
        $exported = (Get-Module PSVellumPDF).ExportedFunctions.Keys
        $exported | Should -Contain 'New-VellumPdfDocument'
        $exported | Should -Contain 'Add-VellumPdfHeading'
        $exported | Should -Contain 'Add-VellumPdfParagraph'
        $exported | Should -Contain 'Save-VellumPdfDocument'
    }
}

Describe 'PDF generation pipeline' {
    BeforeEach {
        $script:outPath = Join-Path $TestDrive "doc-$([guid]::NewGuid()).pdf"
    }

    It 'produces a non-empty PDF file with a valid header' {
        New-VellumPdfDocument |
            Add-VellumPdfHeading -Text 'Smoke Test' -Level 1 |
            Add-VellumPdfParagraph -Text 'Generated by PSVellumPDF.' |
            Save-VellumPdfDocument -Path $script:outPath

        Test-Path $script:outPath | Should -BeTrue
        (Get-Item $script:outPath).Length | Should -BeGreaterThan 0

        # Every PDF starts with the "%PDF-" magic bytes.
        $head = [System.Text.Encoding]::ASCII.GetString(
            [System.IO.File]::ReadAllBytes($script:outPath)[0..4])
        $head | Should -Be '%PDF-'
    }

    It 'creates a PDF/A-2b conformant document' {
        New-VellumPdfDocument -Conformance PdfA2b -PageSize Letter |
            Add-VellumPdfParagraph -Text 'Archival text.' |
            Save-VellumPdfDocument -Path $script:outPath

        (Get-Item $script:outPath).Length | Should -BeGreaterThan 0
    }
}
